openapi: 3.0.0
info:
  title: caferna
  version: "1.0.0"
servers:
- url: https://api.server.test/v1
- url: http://localhost:8080
paths:
  /game:
    get:
      summary: List Games
      operationId: listGames
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
                x-content-type: application/json
        "400":
          description: Invalid status value
      security:
      - caferna_auth:
        - write:games
        - read:games
      x-swagger-router-controller: Default
    post:
      summary: Create a new game
      operationId: createGame
      # requestBody:
      #   $ref: '#/components/requestBodies/Game'
      responses:
        "200":
          description: Game successfully created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
                x-content-type: application/json
        "405":
          description: Invalid input
      security:
      - caferna_auth:
        - write:game
        - read:game
      x-swagger-router-controller: Default
  /game/{gameId}/space:
    get:
      summary: List Game Spaces
      operationId: listGameSpaces
      parameters:
        - $ref: '#/components/parameters/gameId'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Space'
                x-content-type: application/json
        "400":
          description: Invalid status value
      security:
      - caferna_auth:
        - write:games
        - read:games
      x-swagger-router-controller: Default
  /game/{gameId}/player:
    get:
      summary: List Game Players
      operationId: listGamePlayers
      parameters:
        - $ref: '#/components/parameters/gameId'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
                x-content-type: application/json
        "400":
          description: Invalid status value
      security:
      - caferna_auth:
        - write:games
        - read:games
      x-swagger-router-controller: Default
  /game/{gameId}/space/{spaceId}/player/{playerId}/dwarf/{dwarfId}:
    post:
      summary: Player use dwarf in a space
      operationId: useSpace
      parameters:
        - $ref: '#/components/parameters/gameId'
        - $ref: '#/components/parameters/spaceId'
        - $ref: '#/components/parameters/playerId'
        - $ref: '#/components/parameters/dwarfId'
      responses:
        "200":
          description: Dwarf successfully placed on space
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Space'
                x-content-type: application/json
        "405":
          description: Invalid input
      security:
      - caferna_auth:
        - write:game
        - read:game
      x-swagger-router-controller: Default
components:
  parameters:
    gameId:
      name: gameId
      in: path
      description: Game ID
      required: true
      schema:
        type: integer
        format: int32
    spaceId:
      name: spaceId
      in: path
      description: Space ID
      required: true
      schema:
        type: string
    playerId:
      name: playerId
      in: path
      description: Player ID
      required: true
      schema:
        type: string
    dwarfId:
      name: dwarfId
      in: path
      description: Dwarf ID
      required: true
      schema:
        type: string
  schemas:
    Dwarf:
      type: object
      properties:
        id:
          type: string
        weapon:
          type: integer
          format: int32
        isNewBorn:
          type: boolean
    Player:
      type: object
      properties:
        id:
          type: string
        color:
          type: string
        isInitialPlayer:
          type: boolean
        dwarfs:
          type: array
          items:
            $ref: '#/components/schemas/Dwarf'
    Space:
      type: object
      properties:
        gameId:
          type: integer
          format: int32
        id:
          type: string
        name:
          type: string
        nexus:
          type: string
        dwarf:
          type: object
          $ref: '#/components/schemas/Dwarf'
    Game:
      type: object
      properties:
        id:
          type: integer
          format: int32
        numPlayers:
          type: integer
          format: int32
          default: 4
        created:
          type: string
          format: date-time
        ready:
          type: boolean
          default: false
        roundNumber:
          type: integer
          format: int32
        turnPlayerId:
          type: string
        initialPlayerId:
          type: string
      example:
        created: 2000-01-23T04:56:07.000+00:00
        ready: false
        id: 0
        numPlayers: 6
  requestBodies:
    Game:
      description: Game object that needs to be created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Game'
      required: true
  securitySchemes:
    caferna_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://caferna.swagger.io/oauth/dialog
          scopes:
            write:games: modify games in your account
            read:games: read your games
